runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: lxml
  version: latest

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /.*
  script: main.app
  login: admin
  secure: always

builtins:
- deferred: on

skip_files: |
  ^(.*/)?(
  (_backup/.*)|
  (\.cache/.*)|
  (\.idea/.*)|
  (app\.yaml)|
  (app\.yml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (.*\.scss)|
  (\..*)|
  (README\.md)|
  (README\.pdf)|
  (LICENSE)|
  )$
